### ISSUE TITLE
German numbers errors

### ISSUE THREAD

**Issue by shantipriyap** [idiap/asrt#5]
017688088605 is not unformatted
3tägige is not unformatted

**Comment by shantipriyap** [comment]
Uppder case double s is not there. 1E9E

**Comment by shantipriyap** [comment]
10jährige
0190dialer
suite101de
0180telefonnummer

**Comment by shantipriyap** [comment]
telefon 4940414311515 fax 49401802499549

**Comment by shantipriyap** [comment]
gemäss 312e absender

**Comment by alexnanchen** [comment]
All fixed.
